### ISSUE TITLE
bash logging to remote syslog server

### ISSUE THREAD

**Issue by hackersunny** [cyberbutler/bash-logging-elk#1]
Hi!
could you show me how can I send bash logs to remote syslog server?

Thanks and best regards,
Mohammad Zafrul Hasan

**Comment by cyberbutler** [comment]
Sorry, sending bash logs to a syslog server is outside the scope of this project in particular, but it should not be unlike any other log you'd wish to send. A quick search on the internet provided the following resource to me, perhaps it will help you: 
https://www.rsyslog.com/sending-messages-to-a-remote-syslog-server/
